iOS fix
sindresorhus/copy-text-to-clipboard pull request #13
Opened 2017-08-10 22:49 UTC by Matt-Jensen

iOS devices (of the ones I was able to test) were unable to successfully copy any unicorns to their clipboard.

Visiting the [current demo code](https://jsfiddle.net/sindresorhus/6406v3pf) with an iOS ~v10.3 device should show the unintended behavior.

After reviewing the project Cheval I found they resolved this issue [by applying a selectionStart and selectionEnd to the appended textarea](https://github.com/ryanpcmcquen/cheval/blob/gh-pages/cheval.js#L140) so iOS devices would be able to copy the expected number of unicorns.  Please see [my example codepen with the proposed update](https://codepen.io/_mattjensen/pen/KvqomK) for a reference.

2017-08-10 23:02 UTC, sindresorhus requested changes

2017-08-10 23:02 UTC, sindresorhus commented on package.json
> +  "version": "1.0.3",
Don't bump version in a pull request. It's up to the maintainers when, how, and what version to bump.

2017-08-10 23:02 UTC, sindresorhus commented on index.js
> +	el.selectionStart = 0;
Add a comment above here that this is a workaround for iOS.

2017-08-14 14:42 UTC, Matt-Jensen commented
Please let me know if you would like any other updates.

2017-08-20 08:08 UTC, sindresorhus approved these changes

2017-08-20 08:08 UTC, merged

2017-08-20 08:08 UTC, sindresorhus commented
Great! Thank you :)